@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "Shortcut Storage" #F4F6F6{
Class "<<interface>>\nShortcutStorage" as ShortcutStorage
Class JsonShortcutStorage
Class JsonSerializableShortcutMap
}

package "AddressBook Storage" #F4F6F6{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedLocation
Class JsonAdaptedTag
Class NoteContent
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -left-> "1" UserPrefsStorage
StorageManager -right-> "1" ShortcutStorage
StorageManager -down-> "1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> ShortcutStorage
Storage -down-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonShortcutStorage .up.|> ShortcutStorage
JsonShortcutStorage ..> JsonSerializableShortcutMap
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "*" JsonAdaptedLocation
JsonSerializableAddressBook --> "*" NoteContent
JsonAdaptedLocation --> "*" JsonAdaptedTag

@enduml
